assassinmanagerproj/assassinmanagerproj/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'assassinmanagerproj.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r"^", include("mainapp.urls", namespace="mainapp")),
)

# serve source media files in debug mode so that we can see them during 
# development, but not when live
if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assassinmanagerproj/mainapp/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns("",
    url(r"^$", 'mainapp.views.requestIndex', name="index"),
    url(r"^profile/(?P<username>[0-9a-zA-Z]+)/$", 'mainapp.views.requestProfile', name="view_profile"),
    url(r"^edit_profile/$", 'mainapp.views.editProfile', name="edit_profile"),
    url(r"^search_profile/$", 'mainapp.views.searchProfile', name="search_profile"),
    url(r"^games/$", 'mainapp.views.requestAllGames', name="all_games"),
    # url for requesting info on a specific game
    url(r"^games/(?P<gameSlug>[\w-]+)/$", 'mainapp.views.requestSpecificGame', name="specific_game"),
    url(r"^games/(?P<gameSlug>[\w-]+)/history/$", 'mainapp.views.getHistoryForGame', name="game_history"),
    url(r"^games/(?P<gameSlug>[\w-]+)/user_history/(?P<username>[0-9a-zA-Z]+)/$", 'mainapp.views.getHistoryForGameUser', name="user_game_history"),
    url(r"^get_latest/$", 'mainapp.views.getLatest', name="get_latest"),
    url(r"^join_game/(?P<gameSlug>[\w-]+)/$", 'mainapp.views.joinGame', name="join_game"),
    url(r"^invite_people/(?P<gameSlug>[\w-]+)/$", 'mainapp.views.invitePeople', name="invite_people"),
    url(r"^invite_admin_people/(?P<gameSlug>[\w-]+)/$", 'mainapp.views.inviteAdminPeople', name="invite_admin_people"),
    url(r"^leave_game/(?P<gameSlug>[\w-]+)/$", 'mainapp.views.leaveGame', name="leave_game"),
    url(r"^approve/(?P<gameSlug>[\w-]+)/(?P<userID>\d+)/(?P<approve>\d+)/$", 'mainapp.views.approve', name="approve"),
    url(r"^remove_admin/(?P<gameSlug>[\w-]+)/(?P<userID>\d+)/$", 'mainapp.views.removeAdmin', name="remove_admin"),
    url(r"^remove_player/(?P<gameSlug>[\w-]+)/(?P<userID>\d+)/$", 'mainapp.views.removePlayer', name="remove_player"),    
    url(r"^startGame/(?P<gameSlug>[\w-]+)/$", 'mainapp.views.startGame', name="start_game"),
    url(r"^about/$", 'mainapp.views.requestAbout', name="about"),
    url(r"^deleteGame/(?P<gameSlug>[\w-]+)/$", 'mainapp.views.deleteGame', name="delete_game"),
    url(r"^get_target/(?P<gameSlug>[\w-]+)/$", 'mainapp.views.getTarget', name="get_target"),
    url(r"^report_event/(?P<gameSlug>[\w-]+)/$", 'mainapp.views.reportEvent', name="report_event"),

    url(r"^createGame/$", "mainapp.views.createGame", name="create_game"),

    url(r'^register/$', 'mainapp.views.register', name='register'),
    url(r'^confirm_acct/(?P<code>\w+)/$', 'mainapp.views.confirm_acct', name='confirm_acct'),
    url(r'^reset_password/(?P<code>\w+)/$', 'mainapp.views.reset_password', name='reset_password'),
    url(r'^forgotPassword/$', 'mainapp.views.forgotPassword', name='forgot_password'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name':'mainapp/login.html'}, name='login'),
    url(r'^help/$', 'mainapp.views.help', name='help'),
    # Route to logout a user and send them back to the login page
    url(r'^logout/$', 'django.contrib.auth.views.logout', 
        {"next_page": "mainapp:index"}, name="logout"),
)

assassinmanagerproj/mainapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseServerError, HttpResponseRedirect

from django.conf import settings

from django.core.exceptions import ObjectDoesNotExist

from django.utils.crypto import get_random_string
from django.db import transaction

from mainapp.forms import RegistrationForm, GameForm, ReportForm, EditProfileForm, ForgotPasswordForm, ResetPasswordForm, InviteForm, InviteAdminForm, SearchUserForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from mainapp.models import Profile, Game, Participant, Event
from django.db.models import Q

from django.core.mail import send_mail, EmailMultiAlternatives

from django.contrib import messages

import textwrap
import smtplib
import urllib

from  datetime import datetime, date

import copy, random


def checkIfConfirmedUser(request):
    return (request.user.is_active == True and Profile.objects.get(user=request.user).active == True)

def insertSearchBox(context):
    context["searchbox"] = SearchUserForm()
    
def requestIndex(request, context={}):
    insertSearchBox(context)
    renderPassedErrors(context)
    if (request.user.is_authenticated == True):
        context["logged_in"] = "You are currently logged in"
    else:
        context["logged_in"] = "You are not currently logged in"

    return render(request, 'mainapp/index.html', context)


def sendEmail(request, email, verificationCode, name, isNewUser):
    if isNewUser:
        subject = 'Assassin: The Game Confirmation Email'
    else:
        subject = 'Assassin: The Game Forgot Password Link Email'

    fromEmail = '15437team1@gmail.com'
    recipients = [email]
    if isNewUser:
        validationRelLink = "/confirm_acct/%s" % verificationCode
    else:
        validationRelLink = "/reset_password/%s" % verificationCode

    validationAbsLink = request.build_absolute_uri(validationRelLink)

    validationHtmlTag = "<a href='%s'>%s</a>" % (validationAbsLink, 
                                                 validationAbsLink)
    if isNewUser:
        text_content = textwrap.dedent("""
        Hello %s, 

        Thank you for registering for Assassin: The Game. 

        Visit the following link to validate your account:
        %s

        If the link doesnt work, copy and paste this link into your browser's address bar:
        %s

        Thanks!
        """) % (name, validationHtmlTag, validationAbsLink) 
    else:
        text_content = textwrap.dedent("""
        Hello %s, 

        Thank you for using Assassin: The Game. 

        Visit the following link to reset your account:
        %s

        If the link doesnt work, copy and paste this link into your browser's address bar:
        %s

        Thanks!
        """) % (name, validationHtmlTag, validationAbsLink) 

    html_content = text_content.replace("\n", "<br>")
    
    msg = EmailMultiAlternatives(subject, text_content, fromEmail, recipients)
    msg.attach_alternative(html_content, "text/html")
    msg.send()

def register(request):
    context = {}
    insertSearchBox(context)

    # Just display the registration form if this is a GET request
    if request.method == "GET":
        context["form"] = RegistrationForm()
        return render(request, 'mainapp/register.html', context)

    with transaction.atomic():
        form = RegistrationForm(request.POST, request.FILES)
        context['form'] = form
        if not form.is_valid():
            return render(request, 'mainapp/register.html', context)

        # Creates the new user from the valid form data
        new_user = User.objects.create_user(username=form.cleaned_data['username'],
                                            password=form.cleaned_data['password1'],
                                            first_name=form.cleaned_data['first_name'],
                                            last_name=form.cleaned_data['last_name'],
                                            email=form.cleaned_data['email'])
        new_user.save()

    #generate a random number
    code = get_random_string(length=20)

    profile = Profile(    user=new_user, 
                        verificationCode=code, 
                        active=False, 
                        image=request.FILES['prof_pic'])
    sendEmail(request, request.POST['email'], code, request.POST['first_name'], True)
    profile.save()

    new_user = authenticate(username=request.POST['username'], \
                            password=request.POST['password1'])
    login(request, new_user)


    # Logs in the new user and redirects to his/her todo list
    return requestIndex(request, context)


@transaction.atomic
@login_required
def confirm_acct(request, code):
    context = {}
    insertSearchBox(context)
    if (request.user.is_active == True and Profile.objects.get(user=request.user).active == True):
        context['errors'] = ['You already confirmed your account. Why are you confirming again?']
        return requestIndex(request, context)

    try:
        verified = Profile.objects.get(verificationCode=str(code), user=request.user)
        verified.active = True
        verified.save()
    except ObjectDoesNotExist:
        context['errors'] = ['The verification code is incorrect. Please follow the link through your email']
        return requestIndex(request, context)

    context['confirmed'] = 'Congrats! Your account is now confirmed! You can now start using the site.'
    return requestIndex(request, context)



@transaction.atomic
def forgotPassword(request):
    context = {}
    insertSearchBox(context)

    if (request.user.is_active == True and Profile.objects.get(user=request.user).active == True):
        context['errors'] = ['You have already logged in. Why are you trying to access forgot password page?']
        return requestIndex(request, context)
    if request.method == "GET":
        context["form"] = ForgotPasswordForm()
        return render(request, 'mainapp/forgot_password.html', context)

    form = ForgotPasswordForm(request.POST)
    context['form'] = form
    if not form.is_valid():
        return render(request, 'mainapp/forgot_password.html', context)
    try:
        userRequested = User.objects.get(username=form.cleaned_data['username'])
    except:
        context['errors'] = ['Alias does not exist. ']
        context["form"] = ForgotPasswordForm()
        return render(request, 'mainapp/forgot_password.html', context)


    #generate a random number
    code = get_random_string(length=20)
    requestedProfile = Profile.objects.get(user=userRequested)
    requestedProfile.passwordVerification = code
    sendEmail(request, userRequested.email, code,userRequested.first_name, False)
    requestedProfile.save()

    context["please_confirm"] = "Please follow the link through your email to reset your password"

    return requestIndex(request, context)

@transaction.atomic
def reset_password(request, code):
    context = {}
    insertSearchBox(context)

    if (request.user.is_active == True and Profile.objects.get(user=request.user).active == True):
        context['errors'] = ['You have already logged in. Why are you trying to reset your password?']
        return requestIndex(request, context)
    try:
        requestedProfile = Profile.objects.get(passwordVerification=code)
    except:
        context['errors'] = ['Invalid Reset Password Link']
        return requestIndex(request, context)

    if request.method == "GET":
        data = {"code": code}
        context["form"] = ResetPasswordForm(initial=data)
        return render(request, 'mainapp/reset_password.html', context)

    form = ResetPasswordForm(request.POST)
    context['form'] = form
    if not form.is_valid():
        return render(request, 'mainapp/reset_password.html', context)

    user = requestedProfile.user

    user.set_password(form.cleaned_data['password1'])


    user.save()
    requestedProfile.passwordVerification = ""
    requestedProfile.save()


    context["please_confirm"] = "Please log in with your new password"

    return requestIndex(request, context)
 
@login_required
def requestProfile(request, username):
    context = {}
    username = urllib.unquote(username)
    profileUser = User.objects.filter(username__iexact=username)[0]

    context["finished"] = False
    context['playing'] = False
    for game in profileUser.participantIn.all():
        if game.finished == True:
            context["finished"] =True
        else:
            context['playing'] = True

    context["profileUser"] = profileUser
    insertSearchBox(context)

    return render(request, "mainapp/profile.html", context)

def searchProfile(request):
    context = {}
    form = SearchUserForm(request.POST)
    context['searchbox'] = form
    if not form.is_valid():
        context["passed_errors"] = ["Invalid User!"]
        return requestIndex(request, context)
        # before = request.GET.get('from', None)
        # messages.success(request, "Invalid User!")
        # return HttpResponseRedirect(before)
    return requestProfile(request, form.cleaned_data['username'])

@login_required
@transaction.atomic
def editProfile(request):
    context = {}
    insertSearchBox(context)

    if request.method == "GET":
        defaultData = {
            "email": request.user.email,
            "first_name": request.user.first_name,
            "last_name": request.user.last_name
        }
        context["editForm"] = EditProfileForm(request.user, initial=defaultData)
        return render(request, "mainapp/editProfile.html", context)
    
    form = EditProfileForm(request.user, request.POST, request.FILES)

    if not form.is_valid():
        context["editForm"] = form

assassinmanagerproj/mainapp/templates/mainapp/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>{% block 'title' %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/style.css' %}" />
    {% block 'styles' %}{% endblock %}
</head>
<body>
    <header id="main-header" class="navbar navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a id="site-title" class="navbar-brand" href="{% url 'mainapp:index' %}">Assassin</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul id="site-header-tabs" class="nav navbar-nav">
                    <li><a href="{% url 'mainapp:index' %}">Home</a></li>
                    <li><a href="{% url 'mainapp:all_games' %}">Games</a></li>
                    <li><a href="{% url 'mainapp:help' %}">Help</a></li>
                    <!--<li><a href="{% url 'mainapp:about' %}">About</a></li>-->
                </ul>

                {% if user.is_authenticated %}
                    <form id="nav-search-form" class="form navbar-form navbar-left" role="search" action="{% url 'mainapp:search_profile'%}" method="post" >
                        <div class="form-group">
                            <input class="form-control " id="id_username" maxlength="30" name="username" type="text" placeholder="Alias Search">
                        </div>
                        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                        {% csrf_token %}
                    </form>
                {% endif %}

                <div class="pull-right">
                    {% if user.is_authenticated %}
                        <!-- button to use for the logged in user -->
                        <div class="btn-group navbar-btn">
                            <button id="user-button"
                                type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                <span>{{ user.username }}</span>
                                {% if user.first_name or user.last_name %}
                                    <small>({{ user.first_name }} {{ user.last_name }})</small>
                                {% endif %}
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu pull-right" role="menu">
                                <li>
                                    <a href="{% url 'mainapp:view_profile' user.username|urlencode:"" %}">
                                        <span class="glyphicon glyphicon-user"></span>&nbsp
                                        Profile&nbsp
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'mainapp:logout' %}">
                                        <span class="glyphicon glyphicon-off"></span>&nbsp
                                        Logout
                                    </a>
                                </li>
                            </ul>
                        </div>
                    {% else %}
                        <a href="{% url 'mainapp:login' %}" type="button" 
                           class="btn btn-primary navbar-btn">Login</a>
                        <a href="{% url 'mainapp:register' %}" type="button" 
                           class="btn btn-default navbar-btn">Register</a>
                    {% endif %}
                </div>
            </div><!--/.nav-collapse -->
        </div>
    </header>

    <div id="main-content" class="container">
        {% for error in errors%}
            <div class="alert alert-danger" style="margin-top: 10px;">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ error }}
            </div>
        {% endfor%}

        {% for message in messages %}
            <div class="alert alert-danger" style="margin-top: 10px;">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{  message }}
            </div>
        {% endfor%}
  
  
        {% for news in goodnews%}
            <div class="alert alert-success" style="margin-top: 10px;">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ news }}
            </div>
        {% endfor%}

        {% if user.is_authenticated and not user.profile.active %}
            <div class="alert alert-success" style="margin-top: 10px;">
                Please confirm your account through your email. The Email might have arrived in your spam folder.
            </div>
        {% endif %}

        {% if confirmed %}
            <div class="alert alert-success" style="margin-top: 10px;">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ confirmed }}
            </div>
        {% endif %}

        {% if please_confirm %}
            <div class="alert alert-success" style="margin-top: 10px;">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ please_confirm }}
            </div>
        {% endif %}

        {% block 'body' %}{% endblock %}

        <hr>
        <small>
            <strong>Disclaimer:</strong> This website, its creators, and the game in no way condone actual violence against any person or group of people. The game of Assassins (<a href="http://en.wikipedia.org/wiki/Assassin_(game)">wikipedia page</a>) is a <strong>GAME</strong> meant only for the entertainment of all participants. Be kind.
        </small>
    </div><!-- /.container -->

    <script src="{% static 'mainapp/js/jquery-1.11.0.min.js' %}"></script>
    <script src="{% static 'mainapp/js/bootstrap.min.js' %}"></script>
    {% block 'scripts' %}{% endblock %}
</body>
</html>

assassinmanagerproj/mainapp/templates/mainapp/forgot_password.html
{% extends 'mainapp/base.html' %}

{% block 'body' %}
<div class="form-container-md">
    <form class="form" role="form" method="post" action="{% url 'mainapp:forgot_password'%}">
        {% csrf_token %}
        {% include 'mainapp/renderForm.html' with form=form %}
        <button id="post_button" class="btn btn-lg btn-primary btn-block btn-submit" type="submit">Submit</button>
    </form>
</div>

{% endblock %}

assassinmanagerproj/mainapp/templates/mainapp/game.html
{% extends 'mainapp/base.html' %}
{% block 'title' %}{{game.name}}{% endblock %}
{% block 'body' %}
    <div class="page-header">
        <h1>{{ game.name }}</h1>

        {% if game.auto_approve %}
            <h4><span class="label label-success">Auto Approve Enabled</span></h4>
        {% else %}
            <h4><span class="label label-warning">Auto Approve Disabled</span></h4>
        {% endif %}

        <ol class="breadcrumb custom-breadcrumb">
            <li><a href="{% url 'mainapp:all_games' %}">All games</a></li>
            <li class="active">{{ game.name }}</li>
        </ol>
    </div>

    <div class="row">
        <div class="col-xs-1">
        </div>
        <div class="col-xs-4 time-col text-center">
            <h1>Start Time</h1>
            <hr>
        </div>
        <div class="col-xs-2">
        </div>
        <div class="col-xs-4 time-col text-center">
            <h1>End Time</h1>
            <hr>
        </div>
        <div class="col-xs-1">
        </div>
    </div>
    <div class="row">
        {% if game.finished %}
            <div class="col-xs-6 time-col text-center">
                <h3 class="time">{{ game.start_date }}</h3>
            </div>
            <div class="col-xs-6 time-col text-center">
                <h3 class="time">{{ lastevent.time_of_death }}</h3>
            </div>
        {% elif game.started %}
            <div class="col-xs-6 time-col text-center">
                <h3 class="time">{{ game.start_date }}</h3>
            </div>
            <div class="col-xs-6 time-col text-center">
                <h3>In Progress</h3>
            </div>
        {% else %}
            <div class="col-xs-6 time-col text-center">
                <h3 class="time">(Estimated) {{ game.start_date }}</h3>
            </div>
            <div class="col-xs-6 time-col text-center">
                <h3>Yet to Begin</h3>
            </div>
        {% endif %}
    </div>
    <hr>
    
    {% if user.is_authenticated %}
        <div class="row">
            <div class="col-xs-6">
                {% if participant %}

                    {% if requested_participant %}
                        <h2><small>You requested to join this game</small></h2>
                    {% else %}
                        <h2><small>You are participating in this game</small></h2>
                    {% endif %}

                    {% if not game.started %}
                        <a href="{% url 'mainapp:leave_game' game.slug %}" class="btn btn-default">Leave Game</a>
                    {% endif %}
                    {% if view_target %}
                        <a href="{% url 'mainapp:get_target' game.slug %}" class="btn btn-primary">Your current target</a>
                    {% elif game.finished and game.winner == user %}
                        <p class="accent-text positive">You are the winner of this tournament.</p>
                    {% elif game.started and not view_target %}
                        <p class="accent-text negative">You have been eliminated from the game.</p>
                    {% endif %}
                    {% if report %}
                        <a href="{% url 'mainapp:report_event' game.slug %}" class="btn btn-default">Report Assassination</a>
                    {% endif %}
                {% else %}
                    {% if accept_invite %}
                        <h2><small>You are not participating in this game but you have been invited to join</small></h2>
                        <a href="{% url 'mainapp:join_game' game.slug %}" class="btn btn-default">Accept Invite</a>
                        <a href="{% url 'mainapp:leave_game' game.slug %}" class="btn btn-default">Decline Invite</a>
                    {% else %}
                        <h2><small>You are not participating in this game</small></h2>
                    {% endif %}
                    {% if can_join %}
                        <a href="{% url 'mainapp:join_game' game.slug %}" class="btn btn-default">Join Game</a>
                    {% endif %}
                {% endif %}
            </div>
            <div class="col-xs-6">
                {% if is_admin %}
                    <h2><small>You are an admin for this game</small></h2>
                    <!--<a href="#remove-admin-status" class="btn btn-default">Remove Admin Status</a>-->
                    {% if not game.started %}
                        <h2><small>You need to manually press the start game button to begin the game <br> </small></h2>
                        <a href="{% url 'mainapp:start_game' game.slug %}" class="btn btn-default">Start Game</a>
                    {% endif %}


                    {% if not game.finished %}
                        <a href="{% url 'mainapp:delete_game' game.slug %}" class="btn btn-default">Delete Tournament</a>
                    {% endif %}
                    {% if not game.started %}
                        <a href="{% url 'mainapp:invite_people' game.slug %}" class="btn btn-default">Invite People</a>
                    {% endif %}
                    {% if not game.finished %}
                    <a href="{% url 'mainapp:invite_admin_people' game.slug %}" class="btn btn-default">Invite Admin</a>
                    {% endif %}
                {% else %}
                    <h2><small>You are not an admin for this game</small></h2>
                {% endif %}
            </div>
        </div>
        <hr>
    {% endif %}

   
    <header>
        <h2>
            <span>Leaderboard</span>
            <small>{{game.participants.all|length}} current players</small>
            <a href="{% url 'mainapp:game_history' game.slug %}"
               class="pull-right btn btn-default">View game history</a>
        </h2>
    </header>
        {% if activeGameParticipants.all|length or game.participants.all|length %}
            <table class="table">
            {% if activeGameParticipants.all|length %}
                <thead>
                    <tr>
                        <th>Alias</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for participant in activeGameParticipants.all %}
                    <tr>
                        <td>{{participant.person.username}}</td>
                        <td>
                            {% if participant.is_dead %}
                            <span class="accent-text negative">Dead at {{ participant.time_of_death }}</san>
                            {% elif game.finished %}
                            <span class="accent-text positive">Winner</span>
                            {% else %}
                            <span class="accent-text positive">Alive</span>
                            {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'mainapp:user_game_history' game.slug participant.person.username %}" class="btn btn-default">History</a>
                        </td>
                        
                        
                        

                    </tr>
                    {% endfor %}
                </tbody>
            {% else %}
                <thead>
                    <tr>
                        <th>Alias</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in game.participants.all %}
                    <tr>
                        <td>{{user.username}}</td>
                        {% if not game.started and is_admin %} <td>
                        <a href="{% url 'mainapp:remove_player' game.slug user.id %}" class="btn btn-default">Kick Player Out</a>
                    </td>
                    {% endif %}
                    </tr>

                    {% endfor %}
                </tbody>
            {% endif %}
            </table>
        {% endif %}
    {% if not game.auto_approve and game.requested_participants.all|length %}
        <p>Current Waiting To Be Approved Participants ({{game.requested_participants.all|length}})</p>
            {% if game.requested_participants.all|length %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>Name</th>
                             {% if is_admin %}
                            <th>Approve/Deny</th>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in game.requested_participants.all %}
                        <tr>
                            <td>{{user.username }}</td>
                             {% if is_admin %}
                            <td>
                                <a href="{% url 'mainapp:approve' game.slug user.id 1 %}" class="btn btn-default">Approve</a>
                                <a href="{% url 'mainapp:approve' game.slug user.id 0 %}" class="btn btn-default">Reject</a>
                            </td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                No Current Participants
            {% endif %}
    {% endif %}
    {% if game.invited_participants.all|length %}
        <p>Currently Invited Participants ({{game.invited_participants.all|length}})</p>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in game.invited_participants.all %}
                        <tr>
                            <td>{{user.username }}</td>
                            {% if is_admin %}
                            <td>
                                <a href="{% url 'mainapp:approve' game.slug user.id 0 %}" class="btn btn-default">Uninvite</a>
                            </td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
    {% endif %}


    {% if game.admins.all|length  %}
    <p>Admins ({{game.admins.all|length}})</p>
            <table class="table">
                <thead>
                    <tr>
                        <th>Alias</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for admin in game.admins.all %}
                    <tr>
                        <td>{{admin.username}}</td>
                        {% if is_admin  %} {% if admin != user %}
                            <td>
                                <a href="{% url 'mainapp:remove_admin' game.slug admin.id %}" class="btn btn-default">Remove Admin</a>
                            </td>
                            {% endif %}{% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
{% endblock %}